# Generated by Django 2.1 on 2019-01-13 07:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20190113_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='ctime',
            field=models.TimeField(default=datetime.time(13, 8, 22, 992099)),
        ),
    ]
