# Generated by Django 2.1 on 2019-01-13 08:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20190113_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='ctime',
            field=models.TimeField(default=datetime.time(14, 23, 52, 49055)),
        ),
    ]
