# Generated by Django 2.1 on 2019-01-13 09:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20190113_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='ctime',
            field=models.TimeField(default=datetime.time(14, 51, 13, 133459)),
        ),
    ]
